version: '3'

networks:
  integration-tests:
    driver: bridge

services:
  gophermart_tests:
    build:
      context: .
      dockerfile: test.Dockerfile
    environment:
      RUN_ADDRESS: localhost:8080
      DATABASE_URI: postgresql://gophermartuser:gophermartpass@localhost:5432/gophermart
      ACCRUAL_SYSTEM_ADDRESS: accrual:8282
    ports:
      - "8080:8080"
    expose:
      - "8080"
    volumes:
      - .:/go/src/github.com/apolsh/yapr-gophermart/integration-tests
    depends_on:
      - db
      - accrual
    networks:
      - integration-tests
  accrual:
    build:
      context: .
      dockerfile: test.accrual.Dockerfile
    ports:
      - "8282:8282"
    depends_on:
      - db
    networks:
      - integration-tests
  db:
    image: postgres:13.3
    ports:
      - "5432:5432"
    expose:
      - "5432"
    environment:
      POSTGRES_USER: gophermartuser
      POSTGRES_PASSWORD: gophermartpass
      POSTGRES_DB: gophermart
    restart: on-failure
    networks:
      - integration-tests